tiles
tileSpecifications
	^ {
		#ffrfCloister -> 2.
		#ffffCloister -> 4.
		#ccccPennant -> 1.
		#crfr -> 4.
		#cfff -> 5.
		#fcfcPennant -> 2.
		#fcfc -> 1.
		#cfcfCities -> 3.
		#ccffCities -> 2.
		#cfrr -> 3.
		#crrf -> 3.
		#crrr -> 3.
		#ccffPennant -> 2.
		#ccff -> 3.
		#ccrrPennant -> 2.
		#ccrr -> 3.
		#ccfcPennant -> 1.
		#ccfc -> 3.
		#ccrcPennant -> 2.
		#ccrc -> 1.
		#rfrf -> 8.
		#frrf -> 9.
		#frrr -> 4.
		#rrrr -> 1.
	} asDictionary