Class {
	#name : #CCFFreePlace,
	#superclass : #Object,
	#category : 'Carcassonne-Core'
}

{ #category : #accessing }
CCFFreePlace >> easternEdge [
	^ CCFVoidEdge new
]

{ #category : #accessing }
CCFFreePlace >> northernEdge [
	^ CCFVoidEdge new
]

{ #category : #accessing }
CCFFreePlace >> southernEdge [
	^ CCFVoidEdge new
]

{ #category : #accessing }
CCFFreePlace >> westernEdge [
	^ CCFVoidEdge new
]
